// Auto-generated. Do not edit!

// (in-package actionlib_autocharge.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class autochargeGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.goal_ID = null;
    }
    else {
      if (initObj.hasOwnProperty('goal_ID')) {
        this.goal_ID = initObj.goal_ID
      }
      else {
        this.goal_ID = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type autochargeGoal
    // Serialize message field [goal_ID]
    bufferOffset = _serializer.int32(obj.goal_ID, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type autochargeGoal
    let len;
    let data = new autochargeGoal(null);
    // Deserialize message field [goal_ID]
    data.goal_ID = _deserializer.int32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'actionlib_autocharge/autochargeGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '39fe0b47c8126762a51239f3e8cba823';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #goal defintion
    int32 goal_ID 
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new autochargeGoal(null);
    if (msg.goal_ID !== undefined) {
      resolved.goal_ID = msg.goal_ID;
    }
    else {
      resolved.goal_ID = 0
    }

    return resolved;
    }
};

module.exports = autochargeGoal;
