(cl:defpackage actionlib_autocharge-msg
  (:use )
  (:export
   "<AUTOCHARGEACTION>"
   "AUTOCHARGEACTION"
   "<AUTOCHARGEACTIONFEEDBACK>"
   "AUTOCHARGEACTIONFEEDBACK"
   "<AUTOCHARGEACTIONGOAL>"
   "AUTOCHARGEACTIONGOAL"
   "<AUTOCHARGEACTIONRESULT>"
   "AUTOCHARGEACTIONRESULT"
   "<AUTOCHARGEFEEDBACK>"
   "AUTOCHARGEFEEDBACK"
   "<AUTOCHARGEGOAL>"
   "AUTOCHARGEGOAL"
   "<AUTOCHARGERESULT>"
   "AUTOCHARGERESULT"
  ))

