; Auto-generated. Do not edit!


(cl:in-package actionlib_autocharge-msg)


;//! \htmlinclude autochargeFeedback.msg.html

(cl:defclass <autochargeFeedback> (roslisp-msg-protocol:ros-message)
  ((current_pose
    :reader current_pose
    :initarg :current_pose
    :type geometry_msgs-msg:Pose
    :initform (cl:make-instance 'geometry_msgs-msg:Pose)))
)

(cl:defclass autochargeFeedback (<autochargeFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <autochargeFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'autochargeFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name actionlib_autocharge-msg:<autochargeFeedback> is deprecated: use actionlib_autocharge-msg:autochargeFeedback instead.")))

(cl:ensure-generic-function 'current_pose-val :lambda-list '(m))
(cl:defmethod current_pose-val ((m <autochargeFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader actionlib_autocharge-msg:current_pose-val is deprecated.  Use actionlib_autocharge-msg:current_pose instead.")
  (current_pose m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <autochargeFeedback>) ostream)
  "Serializes a message object of type '<autochargeFeedback>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'current_pose) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <autochargeFeedback>) istream)
  "Deserializes a message object of type '<autochargeFeedback>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'current_pose) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<autochargeFeedback>)))
  "Returns string type for a message object of type '<autochargeFeedback>"
  "actionlib_autocharge/autochargeFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'autochargeFeedback)))
  "Returns string type for a message object of type 'autochargeFeedback"
  "actionlib_autocharge/autochargeFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<autochargeFeedback>)))
  "Returns md5sum for a message object of type '<autochargeFeedback>"
  "8aa49ba45d5b9d2df8a650fff8d23e31")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'autochargeFeedback)))
  "Returns md5sum for a message object of type 'autochargeFeedback"
  "8aa49ba45d5b9d2df8a650fff8d23e31")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<autochargeFeedback>)))
  "Returns full string definition for message of type '<autochargeFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%geometry_msgs/Pose current_pose~%~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'autochargeFeedback)))
  "Returns full string definition for message of type 'autochargeFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%geometry_msgs/Pose current_pose~%~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <autochargeFeedback>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'current_pose))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <autochargeFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'autochargeFeedback
    (cl:cons ':current_pose (current_pose msg))
))
