; Auto-generated. Do not edit!


(cl:in-package actionlib_autocharge-msg)


;//! \htmlinclude autochargeResult.msg.html

(cl:defclass <autochargeResult> (roslisp-msg-protocol:ros-message)
  ((final_pose
    :reader final_pose
    :initarg :final_pose
    :type geometry_msgs-msg:Pose
    :initform (cl:make-instance 'geometry_msgs-msg:Pose)))
)

(cl:defclass autochargeResult (<autochargeResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <autochargeResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'autochargeResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name actionlib_autocharge-msg:<autochargeResult> is deprecated: use actionlib_autocharge-msg:autochargeResult instead.")))

(cl:ensure-generic-function 'final_pose-val :lambda-list '(m))
(cl:defmethod final_pose-val ((m <autochargeResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader actionlib_autocharge-msg:final_pose-val is deprecated.  Use actionlib_autocharge-msg:final_pose instead.")
  (final_pose m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <autochargeResult>) ostream)
  "Serializes a message object of type '<autochargeResult>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'final_pose) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <autochargeResult>) istream)
  "Deserializes a message object of type '<autochargeResult>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'final_pose) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<autochargeResult>)))
  "Returns string type for a message object of type '<autochargeResult>"
  "actionlib_autocharge/autochargeResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'autochargeResult)))
  "Returns string type for a message object of type 'autochargeResult"
  "actionlib_autocharge/autochargeResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<autochargeResult>)))
  "Returns md5sum for a message object of type '<autochargeResult>"
  "02829f6272cbde592e4d28921cb69852")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'autochargeResult)))
  "Returns md5sum for a message object of type 'autochargeResult"
  "02829f6272cbde592e4d28921cb69852")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<autochargeResult>)))
  "Returns full string definition for message of type '<autochargeResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result defintion~%geometry_msgs/Pose final_pose~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'autochargeResult)))
  "Returns full string definition for message of type 'autochargeResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result defintion~%geometry_msgs/Pose final_pose~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <autochargeResult>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'final_pose))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <autochargeResult>))
  "Converts a ROS message object to a list"
  (cl:list 'autochargeResult
    (cl:cons ':final_pose (final_pose msg))
))
