; Auto-generated. Do not edit!


(cl:in-package actionlib_autocharge-msg)


;//! \htmlinclude autochargeGoal.msg.html

(cl:defclass <autochargeGoal> (roslisp-msg-protocol:ros-message)
  ((goal_ID
    :reader goal_ID
    :initarg :goal_ID
    :type cl:integer
    :initform 0))
)

(cl:defclass autochargeGoal (<autochargeGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <autochargeGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'autochargeGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name actionlib_autocharge-msg:<autochargeGoal> is deprecated: use actionlib_autocharge-msg:autochargeGoal instead.")))

(cl:ensure-generic-function 'goal_ID-val :lambda-list '(m))
(cl:defmethod goal_ID-val ((m <autochargeGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader actionlib_autocharge-msg:goal_ID-val is deprecated.  Use actionlib_autocharge-msg:goal_ID instead.")
  (goal_ID m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <autochargeGoal>) ostream)
  "Serializes a message object of type '<autochargeGoal>"
  (cl:let* ((signed (cl:slot-value msg 'goal_ID)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <autochargeGoal>) istream)
  "Deserializes a message object of type '<autochargeGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'goal_ID) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<autochargeGoal>)))
  "Returns string type for a message object of type '<autochargeGoal>"
  "actionlib_autocharge/autochargeGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'autochargeGoal)))
  "Returns string type for a message object of type 'autochargeGoal"
  "actionlib_autocharge/autochargeGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<autochargeGoal>)))
  "Returns md5sum for a message object of type '<autochargeGoal>"
  "39fe0b47c8126762a51239f3e8cba823")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'autochargeGoal)))
  "Returns md5sum for a message object of type 'autochargeGoal"
  "39fe0b47c8126762a51239f3e8cba823")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<autochargeGoal>)))
  "Returns full string definition for message of type '<autochargeGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal defintion~%int32 goal_ID ~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'autochargeGoal)))
  "Returns full string definition for message of type 'autochargeGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal defintion~%int32 goal_ID ~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <autochargeGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <autochargeGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'autochargeGoal
    (cl:cons ':goal_ID (goal_ID msg))
))
