// Generated by gencpp from file actionlib_autocharge/autochargeGoal.msg
// DO NOT EDIT!


#ifndef ACTIONLIB_AUTOCHARGE_MESSAGE_AUTOCHARGEGOAL_H
#define ACTIONLIB_AUTOCHARGE_MESSAGE_AUTOCHARGEGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace actionlib_autocharge
{
template <class ContainerAllocator>
struct autochargeGoal_
{
  typedef autochargeGoal_<ContainerAllocator> Type;

  autochargeGoal_()
    : goal_ID(0)  {
    }
  autochargeGoal_(const ContainerAllocator& _alloc)
    : goal_ID(0)  {
  (void)_alloc;
    }



   typedef int32_t _goal_ID_type;
  _goal_ID_type goal_ID;





  typedef boost::shared_ptr< ::actionlib_autocharge::autochargeGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::actionlib_autocharge::autochargeGoal_<ContainerAllocator> const> ConstPtr;

}; // struct autochargeGoal_

typedef ::actionlib_autocharge::autochargeGoal_<std::allocator<void> > autochargeGoal;

typedef boost::shared_ptr< ::actionlib_autocharge::autochargeGoal > autochargeGoalPtr;
typedef boost::shared_ptr< ::actionlib_autocharge::autochargeGoal const> autochargeGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::actionlib_autocharge::autochargeGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::actionlib_autocharge::autochargeGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace actionlib_autocharge

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'actionlib_autocharge': ['/home/lee/catkin_ws/devel/share/actionlib_autocharge/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::actionlib_autocharge::autochargeGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::actionlib_autocharge::autochargeGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::actionlib_autocharge::autochargeGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::actionlib_autocharge::autochargeGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::actionlib_autocharge::autochargeGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::actionlib_autocharge::autochargeGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::actionlib_autocharge::autochargeGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "39fe0b47c8126762a51239f3e8cba823";
  }

  static const char* value(const ::actionlib_autocharge::autochargeGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x39fe0b47c8126762ULL;
  static const uint64_t static_value2 = 0xa51239f3e8cba823ULL;
};

template<class ContainerAllocator>
struct DataType< ::actionlib_autocharge::autochargeGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "actionlib_autocharge/autochargeGoal";
  }

  static const char* value(const ::actionlib_autocharge::autochargeGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::actionlib_autocharge::autochargeGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#goal defintion\n"
"int32 goal_ID \n"
;
  }

  static const char* value(const ::actionlib_autocharge::autochargeGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::actionlib_autocharge::autochargeGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goal_ID);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct autochargeGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::actionlib_autocharge::autochargeGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::actionlib_autocharge::autochargeGoal_<ContainerAllocator>& v)
  {
    s << indent << "goal_ID: ";
    Printer<int32_t>::stream(s, indent + "  ", v.goal_ID);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACTIONLIB_AUTOCHARGE_MESSAGE_AUTOCHARGEGOAL_H
